name: panda tests
on: [push, pull_request]

env:
  RUN: docker run --rm panda /bin/sh -c
  PERSIST: docker run --shm-size 1G --name panda panda /bin/sh -c
  LOAD: docker load -i panda.tar.gz/panda.tar.gz
#  CI_RUN: docker run -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID --rm tmppilotci /bin/bash -c
#  UNIT_TEST: coverage run --append -m unittest discover



jobs:
  docker_build:
    name: docker build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build docker image
      run: |
        #docker pull $(grep -ioP '(?<=^from)\s+\S+' Dockerfile.openpilot) || true
        #docker pull docker.io/commaai/panda:latest || true

        #docker build --cache-from docker.io/commaai/openpilot:latest -t tmppilot -f Dockerfile.openpilot .
        docker build -t panda -f Dockerfile.panda .
        docker save panda:latest | gzip > panda.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: panda.tar.gz
        path: panda.tar.gz

  docker_push:
    name: push
    runs-on: ubuntu-16.04
    needs: docker_build
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/panda'
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Login to dockerhub
        run: docker login -u wmelching -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag image
        run: docker tag panda docker.io/commaai/panda:latest
      - name: Push image
        run: docker push docker.io/commaai/panda:latest

  safety:
    name: safety
    runs-on: ubuntu-16.04
    needs: docker_build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run safety tests
        run: $RUN "cd /tmp/openpilot/panda/tests/safety && ./test.sh"

  safety_replay:
    name: safety replay
    runs-on: ubuntu-16.04
    needs: docker_build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run safety replay
        run: $RUN "cd /tmp/openpilot/panda/tests/safety_replay && ./test_safety_replay.py"

  language_check:
    name: language check
    runs-on: ubuntu-16.04
    needs: docker_build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run language check
        run: $RUN "cd /tmp/openpilot/panda/tests/language && ./test_langugae.py"

  misra:
    name: misra c2012
    runs-on: ubuntu-16.04
    needs: docker_build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run Misra C 2012 analysis
        run: $PERSIST "cd /tmp/openpilot/panda/tests/misra && ./test_misra.sh"
      - name: Copy analysis outputs
        run: docker cp panda:/tmp/openpilot/panda/tests/misra /tmp
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cppcheck.txt
          path: /tmp/misra/cppcheck_output.txt
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: misra.txt
          path: /tmp/misra/misra_output.txt

  python_linter:
    name: python linter
    runs-on: ubuntu-16.04
    needs: docker_build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run linters
        run: |
          $RUN "cd /tmp/openpilot/panda/tests/linter_python/ && ./flake8_panda.sh"
          $RUN "cd /tmp/openpilot/panda/tests/linter_python/ && ./pylint_panda.sh"


