name: panda tests
on: [push, pull_request]

env:
  RUN: docker run --rm tmppilot /bin/sh -c
  PERSIST: docker run --shm-size 1G --name tmppilot tmppilot /bin/sh -c
  LOAD: docker load -i panda.tar.gz/panda.tar.gz
#  CI_RUN: docker run -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID --rm tmppilotci /bin/bash -c
#  UNIT_TEST: coverage run --append -m unittest discover



jobs:
  # TODO: push stage to use for cache
  build:
    name: build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build docker image
      run: |
        #docker pull $(grep -ioP '(?<=^from)\s+\S+' Dockerfile.openpilot) || true
        #docker pull docker.io/commaai/panda:latest || true

        #docker build --cache-from docker.io/commaai/openpilot:latest -t tmppilot -f Dockerfile.openpilot .
        docker build -t panda -f Dockerfile.panda .
        docker save panda:latest | gzip > panda.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: panda.tar.gz
        path: panda.tar.gz

  safety:
    name: safety
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run safety tests
        run: $RUN "cd /tmp/openpilot/panda/test/safety && ./test.sh"

  safety_replay:
    name: safety replay
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run safety replay
        run: $RUN "cd /tmp/openpilot/panda/test/safety_replay && ./test_safety_replay.py"

  language_check:
    name: language check
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run language check
        run: $RUN "cd /tmp/openpilot/panda/test/language && ./test_langugae.py"

  misra:
    name: misra c2012
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run Misra C 2012 analysis
        run: $PERSIST "cd /tmp/openpilot/panda/test/misra && ./test_misra.sh"
      - name: Copy analysis outputs
        run: docker cp panda:/tmp/openpilot/panda/test/misra /tmp
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cppcheck.txt
          path: /tmp/misra/cppcheck_output.txt
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: misra.txt
          path: /tmp/misra/misra_output.txt

