name: panda tests
on: [push, pull_request]

env:
  RUN: docker run --rm tmppilot /bin/sh -c
#  PERSIST: docker run --shm-size 1G --name tmppilot tmppilot /bin/sh -c
  LOAD: docker load -i panda.tar.gz/panda.tar.gz
#  CI_RUN: docker run -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID --rm tmppilotci /bin/bash -c
#  UNIT_TEST: coverage run --append -m unittest discover



jobs:
  # TODO: push stage to use for cache
  build:
    name: build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build docker image
      run: |
        #docker pull $(grep -ioP '(?<=^from)\s+\S+' Dockerfile.openpilot) || true
        #docker pull docker.io/commaai/panda:latest || true

        #docker build --cache-from docker.io/commaai/openpilot:latest -t tmppilot -f Dockerfile.openpilot .
        docker build -t panda f Dockerfile.panda .
        docker save panda:latest | gzip > panda.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: panda.tar.gz
        path: panda.tar.gz

  safety:
    name: safety
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: panda.tar.gz
      - name: Load image
        run: $LOAD
      - name: Run safety tests
        run: $RUN "cd /tmp/openpilot/panda/test/safety && ./test.sh"

